In [1]:
import numpy as np

In [24]:
a = [[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]]

In [25]:
a

[[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]

In [26]:
b = np.array(a)
b

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [27]:
b.shape

(3, 3, 3)

In [28]:
b.ndim

3

# METHODS

In [29]:
x = [1,2,3,4,5]
y = [[1,2,3], [4,5,6], [7,8,9]]

In [30]:
z = np.array(y)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
z.max()

9

In [61]:
z.min()

1

In [68]:
# index of the max value
z.argmax()

8

In [70]:
# index of the min value
z.argmin()

0

In [31]:
z.shape

(3, 3)

In [32]:
z.ndim

2

In [34]:
# zero matrix
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros((3,2,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [39]:
# unit matrix
np.ones(3)

array([1., 1., 1.])

In [45]:
np.ones((3,2,7)).ndim

3

In [44]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
#  since identity matrix is possible only for square matrix
np.eye((3,2))             

TypeError: 'tuple' object cannot be interpreted as an integer

In [56]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [59]:
np.linspace(0,1,2)

array([0., 1.])

In [62]:
np.random.rand(5)

array([0.71922606, 0.90669276, 0.70036289, 0.99980756, 0.91425493])

In [63]:
np.random.randn(5)

array([-0.17222102,  0.44267701,  2.55383885,  0.7501744 , -0.99885355])

In [67]:
np.random.randint(5)

1

In [72]:
p = np.arange(1,20)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [73]:
p[0]

1

In [74]:
p[-1]

19

In [75]:
p[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
p[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [77]:
p[2:5]

array([3, 4, 5])

In [78]:
p[-10:-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [81]:
q = p[5:15] = 40            
# === p[5:15] = 40
q

40

In [80]:
p

array([ 1,  2,  3,  4,  5, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 16, 17,
       18, 19])

In [83]:
s = np.arange(25).reshape(5,5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
s[2][4]

14

In [86]:
s[4][2]

22

In [88]:
s[2,4]

14

In [89]:
s[4,2]

22

In [92]:
s[0:2,2:]
# 0:2  ==> rows
# 2:  ==> columns

array([[2, 3, 4],
       [7, 8, 9]])

In [93]:
# conditional selection
s > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [94]:
s[s > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [128]:
m = np.arange(10).reshape(2,5)
m

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
n = np.arange(10,20).reshape(2,5)
n

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
m - n

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [121]:
o = np.arange(15)
o.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [110]:
m - o

ValueError: operands could not be broadcast together with shapes (2,5) (15,) 

In [111]:
np.log(m)

C:\Users\DELL\AppData\Local\Temp\ipykernel_5336\1204968543.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(m)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458]])

In [126]:
np.max(m)

9

In [129]:
max(m)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [132]:
m.dtype

dtype('int32')

# Documentation

In [133]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [134]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [135]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [136]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [140]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [142]:
array_example.ndim


3

In [143]:
array_example.size

24

In [144]:
array_example.shape

(3, 2, 4)

In [145]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])


In [146]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [147]:
np.hstack((a1, a2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [148]:
x = np.arange(1, 25).reshape(2, 12)

In [149]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [150]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [151]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [152]:
data.max()

2.0

In [153]:
data.min()

1.0

In [154]:
data.sum()

3.0

In [155]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [156]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [157]:
a.min()

0.05093587

In [158]:
a.sum()

4.8595784

In [159]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [160]:
data.max(axis=0)

array([5, 6])

In [161]:
data.max(axis=1)

array([2, 5, 6])

In [163]:
rng = np.random.default_rng()

In [164]:
rng.random(3) 

array([0.95496947, 0.38560724, 0.61916349])

In [166]:
np.random.rand(3)

array([0.64476183, 0.62714899, 0.02231351])

In [167]:
rng.random((3, 2))

array([[0.60877431, 0.25524373],
       [0.26162273, 0.63220804],
       [0.71310175, 0.98325442]])

In [168]:
np.random.rand((3,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [171]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [170]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [172]:
np.flip(a)

array([20, 19, 18, 14, 11, 13, 12, 17, 16, 15, 14, 13, 12, 11, 11])

In [173]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [174]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [175]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [176]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [177]:
np.flip(arr_2d[:,1])

array([10,  6,  2])

In [178]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [179]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [180]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [186]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [191]:
a1 = x.flatten()

In [192]:
a1[0] = 99

In [193]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [194]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [195]:
a2 = x.ravel()

In [196]:
a2[0] = 98

In [197]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [198]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
